services:
  node:
    container_name: chubbyts-petstore-node
    hostname: chubbyts-petstore-node
    build:
      dockerfile: ./docker/development/node/Dockerfile
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      NODE_ENV: development
      MONGO_URI: 'mongodb://petstore:4aAUfBjDACcdZxNwJgJ6@mongo:27017/petstore?authMechanism=DEFAULT&authSource=admin'
      POSTGRES_URI: 'postgres://root:4aAUfBjDACcdZxNwJgJ6@postgres:5432/postgres'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '1234'
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - '1235:1235'
    volumes:
      - ${PWD}:/app
      - ~/.bash_docker:/home/node/.bash_docker
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.gitignore:/home/node/.gitignore
      - ~/.zsh_docker:/home/node/.zsh_docker
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - mongo
  node-fluentd:
    container_name: chubbyts-petstore-node-fluentd
    hostname: chubbyts-petstore-node-fluentd
    build:
      dockerfile: ./docker/production/node-fluentd/Dockerfile
      context: ./
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      STACK: 'local'
      OPENSEARCH_HOSTS: 'opensearch:9200'
      OPENSEARCH_USER: 'admin'
      OPENSEARCH_PASSWORD: 't9V02zfj!NMj?LugFsOi'
      OPENSEARCH_SSL_VERIFY: 'false'
    volumes:
      - ${PWD}/var/log:/app/var/log
    depends_on:
      - opensearch
  postgres:
    container_name: chubbyts-petstore-postgres
    hostname: chubbyts-petstore-postgres
    image: postgres:17
    command: -c log_statement=all -c log_error_verbosity=VERBOSE
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  mongo:
    container_name: chubbyts-petstore-mongo
    hostname: chubbyts-petstore-mongo
    image: mongo:8.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: petstore
      MONGO_INITDB_ROOT_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  nginx:
    container_name: chubbyts-petstore-nginx
    hostname: chubbyts-petstore-nginx
    image: nginx:1.27.5
    environment:
      SERVER_PORT: '443'
      NODE_SERVER_HOST: 'node'
      NODE_SERVER_PORT: '1234'
      SWAGGER_SERVER_HOST: 'swagger-ui'
      SWAGGER_SERVER_PORT: '8080'
    ports:
      - '443:443'
    volumes:
      - ./docker/development/nginx:/etc/nginx/templates
    depends_on:
      - node
      - swagger-ui
  opensearch:
    container_name: chubbyts-petstore-opensearch
    hostname: chubbyts-petstore-opensearch
    image: opensearchproject/opensearch:2.19.2
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 't9V02zfj!NMj?LugFsOi'
      discovery.type: 'single-node'
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sk https://localhost:9200 | grep -q 'Unauthorized'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  opensearch-dashboard:
    container_name: chubbyts-petstore-opensearch-dashboard
    hostname: chubbyts-petstore-opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:2.19.2
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    ports:
      - 5601:5601
  swagger-ui:
    container_name: chubbyts-petstore-swagger-ui
    hostname: chubbyts-petstore-swagger-ui
    image: swaggerapi/swagger-ui:v5.20.1
    environment:
      BASE_URL: /swagger
      URLS: '[ { url: "/openapi" } ]'

volumes:
  mongo:
  postgres:
