services:
  node:
    container_name: chubbyts-petstore-node-ci
    hostname: chubbyts-petstore-node-ci
    build:
      dockerfile: ./docker/production/node/Dockerfile
      context: ./
    environment:
      NODE_ENV: production
      POSTGRES_URI: 'postgres://root:4aAUfBjDACcdZxNwJgJ6@postgres:5432/postgres'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '1234'
    depends_on:
      - postgres
  postgres:
    container_name: chubbyts-petstore-postgres
    hostname: chubbyts-petstore-postgres
    image: postgres:17
    command: -c log_statement=all -c log_error_verbosity=VERBOSE
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
  swagger-ui:
    container_name: chubbyts-petstore-swagger-ui-ci
    hostname: chubbyts-petstore-swagger-ui-ci
    image: swaggerapi/swagger-ui:v5.20.1
    environment:
      BASE_URL: /swagger
      URLS: '[ { url: "/openapi" } ]'
  nginx:
    container_name: chubbyts-petstore-nginx-ci
    hostname: chubbyts-petstore-nginx-ci
    image: nginx:1.27.5
    environment:
      SERVER_PORT: '443'
      NODE_SERVER_HOST: 'node'
      NODE_SERVER_PORT: '1234'
      SWAGGER_SERVER_HOST: 'swagger-ui'
      SWAGGER_SERVER_PORT: '8080'
    ports:
      - '443:443'
    volumes:
      - ./docker/development/nginx:/etc/nginx/templates
    depends_on:
      - node
      - swagger-ui
