version: '3.0'
services:
  node:
    container_name: chubbyts-petstore-node
    hostname: chubbyts-petstore-node
    build:
      dockerfile: ./docker/production/node/Dockerfile
      context: ./
    environment:
      NODE_ENV: production
      MONGO_URI: 'mongodb://petstore:KVKtkrTHhKuTJTor8pCP@mongo:27017/petstore?authMechanism=DEFAULT&authSource=admin'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '1234'
    depends_on:
      - mongo
  mongo:
    container_name: chubbyts-petstore-mongo
    hostname: chubbyts-petstore-mongo
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: petstore
      MONGO_INITDB_ROOT_PASSWORD: KVKtkrTHhKuTJTor8pCP
