version: '3.0'
services:
  node:
    container_name: chubbyts-petstore-node
    hostname: chubbyts-petstore-node
    build:
      dockerfile: ./docker/development/node/Dockerfile
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      NODE_ENV: development
      MONGO_URI: 'mongodb://root:root@mongo:27017/pet?authMechanism=DEFAULT&authSource=admin'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '10080'
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - '10080:10080'
    volumes:
      - ${PWD}:/app
      - ~/.bash_docker:/home/node/.bash_docker
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.gitignore:/home/node/.gitignore
      - ~/.zsh_docker:/home/node/.zsh_docker
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - mongo
  mongo:
    container_name: chubbyts-petstore-mongo
    hostname: chubbyts-petstore-mongo
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - ./database/mongo:/data/db
  swagger-ui:
    container_name: chubbyts-petstore-swagger-ui
    hostname: chubbyts-petstore-swagger-ui
    image: swaggerapi/swagger-ui
    environment:
      BASE_URL: /swagger
      URLS: '[ { url: "/openapi" } ]'
  nginx:
    container_name: chubbyts-petstore-nginx
    hostname: chubbyts-petstore-nginx
    build:
      dockerfile: ./docker/development/nginx/Dockerfile
      context: ./
    environment:
      SERVER_PORT: '10443'
      NODE_SERVER_HOST: 'node'
      NODE_SERVER_PORT: '10080'
      SWAGGER_SERVER_HOST: 'swagger-ui'
      SWAGGER_SERVER_PORT: '8080'
    ports:
      - '10443:10443'
    depends_on:
      - node
