version: '3.0'
services:
  node:
    container_name: chubbyts-petstore-node
    hostname: chubbyts-petstore-node
    build:
      dockerfile: ./docker/development/node/Dockerfile
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    environment:
      NODE_ENV: development
      MONGO_URI: 'mongodb://petstore:4aAUfBjDACcdZxNwJgJ6@mongo:27017/petstore?authMechanism=DEFAULT&authSource=admin'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '1234'
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - '1235:1235'
    volumes:
      - ${PWD}:/app
      - ~/.bash_docker:/home/node/.bash_docker
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.gitignore:/home/node/.gitignore
      - ~/.zsh_docker:/home/node/.zsh_docker
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - mongo
  node-fluentd:
    container_name: chubbyts-petstore-node-fluentd
    hostname: chubbyts-petstore-node-fluentd
    image: bitnami/fluentd:1.15.3
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      FLUENTD_DAEMON_USER: ${USER_ID:-1000}
      FLUENTD_DAEMON_GROUP: ${GROUP_ID:-1000}
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    volumes:
      - ${PWD}/dist/var/log:/app/var/log
      - ${PWD}/fluentd.conf:/opt/bitnami/fluentd/conf/fluentd.conf
    depends_on:
      - elasticsearch
  mongo:
    container_name: chubbyts-petstore-mongo
    hostname: chubbyts-petstore-mongo
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: petstore
      MONGO_INITDB_ROOT_PASSWORD: 4aAUfBjDACcdZxNwJgJ6
    ports:
      - '27017:27017'
    volumes:
      - ./database/mongo:/data/db
  swagger-ui:
    container_name: chubbyts-petstore-swagger-ui
    hostname: chubbyts-petstore-swagger-ui
    image: swaggerapi/swagger-ui:v4.15.5
    environment:
      BASE_URL: /swagger
      URLS: '[ { url: "/openapi" } ]'
  nginx:
    container_name: chubbyts-petstore-nginx
    hostname: chubbyts-petstore-nginx
    image: nginx:1.23.2
    environment:
      SERVER_PORT: '443'
      NODE_SERVER_HOST: 'node'
      NODE_SERVER_PORT: '1234'
      SWAGGER_SERVER_HOST: 'swagger-ui'
      SWAGGER_SERVER_PORT: '8080'
    ports:
      - '443:443'
    volumes:
      - ./docker/development/nginx:/etc/nginx/templates
    depends_on:
      - node
      - swagger-ui
  elasticsearch:
    container_name: chubbyts-petstore-elasticsearch
    hostname: chubbyts-petstore-elasticsearch
    image: elasticsearch:8.5.2
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      bootstrap.memory_lock: 'true'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      xpack.security.enrollment.enabled: 'false'
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: chubbyts-petstore-kibana
    hostname: chubbyts-petstore-kibana
    image: kibana:8.5.2
    environment:
      XPACK_APM_SERVICEMAPENABLED: 'true'
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 0557aa47-1706-48df-8f2b-b7a5eddcbdf2
    ports:
      - 5601:5601
