version: '3.0'
services:
  node:
    container_name: chubbyts-petstore-node
    hostname: chubbyts-petstore-node
    build:
      dockerfile: ./docker/prod/node/Dockerfile
      context: ./
    environment:
      APP_ENV: prod
      MONGO_URI: 'mongodb://root:root@mongo:27017/pet?authMechanism=DEFAULT&authSource=admin'
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '10080'
    ports:
      - '10080:10080'
    depends_on:
      - mongo
  mongo:
    container_name: chubbyts-petstore-mongo
    hostname: chubbyts-petstore-mongo
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
