allowBuilds:
  esbuild: true
  unrs-resolver: true
packageExtensions:
  '@stryker-mutator/core':
    dependencies:
      typescript: ^6.0.3
  '@stryker-mutator/typescript-checker':
    dependencies:
      typescript: ^6.0.3
