allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@chubbyts/chubbyts-undici-trusted-proxy@1.2.0'
packageExtensions:
  '@stryker-mutator/core':
    dependencies:
      typescript: ^6.0.3
  '@stryker-mutator/typescript-checker':
    dependencies:
      typescript: ^6.0.3
